const data = {
    products: [
      {
        _id: '1',
        name: 'Betula Womens Tote Handbag',
        category: 'Handbags',
        image: '/images/p1.jpg',
        price: 1200,
        brand: 'Lavie',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Pamukkale Womens Satchel Handbag',
        category: 'Handbags',
        image: '/images/p2.jpg',
        price: 100,
        brand: 'baggit',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Lacoste Free Handbags',
        category: 'Handbags',
        image: '/images/p3.jpg',
        price: 220,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Ushawu Dome Satchel Womens Handbag',
        category: 'Handbags',
        image: '/images/p4.jpg',
        price: 78,
        brand: 'Capresse',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Odiase Womens Satchel Handbag',
        category: 'Handbags',
        image: '/images/p5.webp',
        price: 65,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Chapada Womens Satchel Handbag',
        category: 'Handbags',
        image: '/images/p6.webp',
        price: 139,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;